### ISSUE TITLE
Any plan for adding the 'Add Package' function?

### ISSUE THREAD

**Issue by eric890006** [tr4nt0r/pyloadapi#40]
Hi,

Thanks for implementing this useful module. Is it possible add the 'Add Package' function so that we can add a download package via command line interface? (I find that CLI is no longer supported in recent pyload versions)

Thanks.

**Comment by tr4nt0r** [comment]
Was not planning yet, i created this library primarily for the [Home Assistant integration](https://www.home-assistant.io/integrations/pyload/), but shouldn't be too difficult to implement.

**Comment by tr4nt0r** [comment]
Added methods to add packages and upload container to pyLoad in release v1.4.0. Also a commandline interface was added. If you install pyloadapi with `pip install pyloadapi[cli]` the optional dependencies for the commadline interface will also be installed. The CLI then can be invoked by typing `pyloadapi` in the commandline.

**Comment by tr4nt0r** [comment]
@eric890006 If you find the time to try the new CLI and add package features I added, i would really appreciate getting some feedback 😊

**Comment by eric890006** [comment]
Hi, @tr4nt0r 

Thanks for the update. Here are some suggestions/findings:
1. In the installlation page (https://tr4nt0r.github.io/pyloadapi/installation/ ), the original installation command is not working anymore?
`$ python setup.py install `
 I tried the following command instead:
`$ pip install .`
However, I find the following error in my environment:
`ERROR: Package 'pyloadapi' requires a different Python: 3.10.12 not in '>=3.11'`
Finally, the error is resolved by adding `--ignore-requires-python`
`$ pip install . --ignore-requires-python`

2.  Since my environment is python3.10, and the StrEnum module from types.py needs python>=3.11, I manually edited the import code and added ReprEnum and StrEnum into types.py:
```
from enum import IntEnum, Enum


class ReprEnum(Enum):
    """
    Only changes the repr(), leaving str() and format() to the mixed-in type.
    """


class StrEnum(str, ReprEnum):
    """
    Enum where members are also (and must be) strings
    """

    def __new__(cls, *values):
        "values must already be of type `str`"
        if len(values) > 3:
            raise TypeError('too many arguments for str(): %r' % (values, ))
        if len(values) == 1:
            # it must be a string
            if not isinstance(values[0], str):
                raise TypeError('%r is not a string' % (values[0], ))
        if len(values) >= 2:
            # check that encoding argument is a string
            if not isinstance(values[1], str):
                raise TypeError('encoding must be a string, not %r' % (values[1], ))
        if len(values) == 3:
            # check that errors argument is a string
            if not isinstance(values[2], str):
                raise TypeError('errors must be a string, not %r' % (values[2]))
        value = str(*values)
        member = str.__new__(cls, value)
        member._value_ = value
        return member

    def _generate_next_value_(name, start, count, last_values):
        """
        Return the lower-cased version of the member name.
        """
        return name.lower()
```

3. Also, I have to change 2 f-strings in the cli.py to avoid some error:
Line 152 from
`f"{"Paused" if s.get("pause") else "Resumed"} download queue."`
to
`f"{'Paused' if s.get('pause') else 'Resumed'} download queue."`
And Line 301 from 
`f"{"Enabled" if s.get("reconnect") else "Disabled"} auto-reconnect"`
to 
`f"{'Enabled' if s.get('reconnect') else 'Disabled'} auto-reconnect"`

4. Final notes: Use `http://localhost:8000/` instead of `http://localhost:8000`. For example:
`pyloadapi --api-url http://localhost:8000/ --username pyload --password pyload status`
I spent some time to figure out why I got the `Unable to connect to pyLoad` error. :joy:

**Comment by tr4nt0r** [comment]
Minimum requirement is Python 3.11. 

About the `python setup.py install`, that's some leftover from the project template i used, sorry for that, will have to update that  ^^ 

The Package is also available on PyPI, so you can just install it with `pip install pyloadapi` or `pip install pyloadapi[cli]` to also install the dependencies for the CLI
